version: '3.9'

services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    command: npm run dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/public:/app/public
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://localhost:4000/live
      - VITE_API_URL=http://localhost:4000/api

  nginx:
    ports:
      - "80:80"
      - "443:443"
